# Generated by Django 3.0.2 on 2020-01-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_no', models.AutoField(primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=255)),
                ('b_note', models.TextField()),
                ('b_writer', models.CharField(max_length=50)),
                ('b_date', models.DateTimeField()),
                ('b_count', models.IntegerField()),
                ('parent_no', models.IntegerField()),
            ],
        ),
    ]
