# Generated by Django 3.0.2 on 2020-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200103_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='parent_no',
            field=models.IntegerField(default=0),
        ),
    ]
